# fly.toml app configuration file generated for newsletter-app-hubptw on 2024-11-25T05:16:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'newsletter-app-hubptw'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
