"""Fix User model

Revision ID: 4470e778b4ad
Revises: 65880c571272
Create Date: 2024-11-14 20:16:18.195039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4470e778b4ad'
down_revision = '65880c571272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Manually add autoincrement to the 'id' column
        batch_op.alter_column('id', type_=sa.Integer(), autoincrement=True, existing_type=sa.Integer(), existing_nullable=False)
        
        # Drop the 'preferred_delivery_time' and 'status' columns if they exist
        batch_op.drop_column('preferred_delivery_time')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Re-add the 'status' and 'preferred_delivery_time' columns if downgrading
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), nullable=True))
        batch_op.add_column(sa.Column('preferred_delivery_time', postgresql.TIME(), nullable=True))

    # ### end Alembic commands ###
