"""adding SubscriptionContent model

Revision ID: 5b7b7a6ca334
Revises: b035a84f3a97
Create Date: 2024-11-18 20:25:54.943238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b7b7a6ca334'
down_revision = 'b035a84f3a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_type', sa.String(length=50), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('fetch_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cached_content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscription_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('cached_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cached_content_pkey')
    )
    op.drop_table('subscription_content')
    # ### end Alembic commands ###
