"""add User and Content tables

Revision ID: 65880c571272
Revises: 
Create Date: 2024-11-14 20:00:59.577352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65880c571272'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('untitled_table')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=200), nullable=False))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('id')

    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)

    op.create_table('untitled_table',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='untitled_table_pkey')
    )
    # ### end Alembic commands ###
